### ISSUE TITLE
ERROR in src/app/giphy.service.ts | Cannot find module 'rxjs-compat'

### ISSUE THREAD

**Issue by Levero** [Levero/giphy-app#1]
```
ERROR in node_modules/rxjs/Rx.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat'.
src/app/giphy.service.ts(3,10): error TS2305: Module '"/Users/Robin/GitHub/giphy-app/node_modules/rxjs/Rx"' has no exported member 'Observable'.
src/app/giphy.service.ts(15,6): error TS2339: Property 'map' does not exist on type 'Observable<Response>'.
src/app/giphy.service.ts(20,6): error TS2339: Property 'map' does not exist on type 'Observable<Response>'.
src/app/giphy.service.ts(25,6): error TS2339: Property 'map' does not exist on type 'Observable<Response>'.

｢wdm｣: Failed to compile.
```

**Comment by Levero** [comment]
Could not find module "@angular-devkit/build-angular" from "/Users/user/Documents/GitHub/giphy-app".
Error: Could not find module "@angular-devkit/build-angular" from "/Users/user/Documents/GitHub/giphy-app".
    at Object.resolve (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/core/node/resolve.js:141:11)
    at Observable.rxjs_1.Observable [as _subscribe] (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect.js:132:40)
    at Observable._trySubscribe (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:30:22)
    at /usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:99:19
    at new Promise (<anonymous>)
    at Observable.toPromise (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:97:16)
    at ServeCommand.initialize (/usr/local/lib/node_modules/@angular/cli/models/architect-command.js:91:94)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by Levero** [comment]
Version 6 of RxJS changed its internal package structure.
